sudo: true
language: android
jdk: oraclejdk8

# based partially on: https://github.com/andstatus/andstatus/blob/master/.travis.yml
env:
  global:
  - ANDROID_API=28
  - EMULATOR_API=23
  - ABI=armeabi-v7a
  - EMULATOR_TAG=android
  - ANDROID_BUILD_TOOLS=27.0.3
  - ADB_INSTALL_TIMEOUT=20 # wait this many minutes for adb to connect to emulator (2 by default)
  # fix Qt for emulator
  - QT_QPA_PLATFORM_PLUGIN_PATH=offscreen
  - LD_LIBRARY_PATH=${ANDROID_HOME}/tools/lib64:${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib

android:
  components:
  - tools
  - tools

before_install:
  - bash .travis-android-license-bugfix.sh
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55\nd56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd\n504667f4c0de7af1a06de9f4b1727b84351f2910" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

before_script:
  - echo yes | sdkmanager --update
  # Install the rest of tools (e.g. avdmanager)
  - yes | sdkmanager tools
  - yes | sdkmanager "system-images;android-23;google_apis;armeabi-v7a"
  - sdkmanager --list || true
  - avdmanager list device
  - echo no | avdmanager -v create avd -f -n test -k "system-images;android-23;google_apis;armeabi-v7a"
  - $ANDROID_HOME/emulator/emulator64-arm -avd test -netfast -no-window -no-audio &

script:
  - ./gradlew assemble -PdisablePreDex;
  - echo "Starting unit tests..."
  - ./gradlew assemble lint build test -PdisablePreDex;
  - travis_wait 10 android-wait-for-emulator
  - adb shell input keyevent 82 &
  # Avoid having it lock itself again.
  - adb shell svc power stayon true
  # Run instrumentation tests
  - echo "Going to run instrumentation tests..."
  - adb shell input keyevent 1 &
  - travis_wait 20 ./gradlew connectedCheck -PdisablePreDex;
  - echo "All done."

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache
